### ISSUE TITLE
Make embedded videos resizable

### ISSUE THREAD

**Issue by Syrious** [wontlost-ltd/vaadin-litelement-ckeditor#71]
Hey there. I just started to use the CKEditorVaadin and I am very impressed. It works great. The only thing that bothers me is that I can't resize a video. It takes always the full width and I haven't found any workaround yet. 

I normally wouldn't open an issue before asking in discord but unfortunately the discord link you provide on the Vaadin Add-on page is not valid.

Anyways, I would love to see this feature one day or at least get a good workaround.

**Comment by jet-pang** [comment]
**Triaged on 5.3.0** — reclassifying as **enhancement** (kept open, labeled `enhancement`).

Verified there's genuinely no public API to make embedded media resizable: `setMediaEmbed(boolean previewsInData)` is the only media-embed config, and although WIDGET_RESIZE and MEDIA_EMBED plugins both ship, **MediaEmbed embeds aren't CKEditor widgets by default**, so WidgetResize can't resize them as-is. So this isn't a one-line config fix — it needs real work (wrap media as a resizable widget or expose `mediaEmbed` resize options + custom view). Tracking as an enhancement rather than a bug. 🤖

**Comment by jet-pang** [comment]
**Triaged & validated against 5.3.0 — keeping open as a tracked enhancement.**

### Why it's not a quick config flag
CKEditor 5 *does* ship resize support for embeds (`MediaEmbedResize` / `MediaEmbedResizeHandles` / `ResizeMediaEmbedCommand`), **but** those plugins live only in the `@ckeditor/ckeditor5-media-embed` subpackage. This addon depends on the **umbrella `ckeditor5` package**, and `MediaEmbedResize` is **not exported from the umbrella's runtime bundle** (verified: 0 occurrences in `ckeditor5/dist/ckeditor5.js`). Pulling it from the subpackage directly would mix umbrella + subpackage imports, which CKEditor explicitly warns against (dual-package / duplicate-module hazards). So a clean `setMediaEmbedResizable(true)` isn't safely implementable today; it's blocked on the umbrella package exposing the resize plugins. Tracking it here for when that lands.

### Workaround you can use now
Embedded media defaults to full container width. To control the size yourself, allow width styling via GeneralHtmlSupport and add a CSS rule (or set inline width):

```java
VaadinCKEditor editor = VaadinCKEditor.create()
        .withPreset(CKEditorPreset.STANDARD)
        .addPlugin(CKEditorPlugin.GENERAL_HTML_SUPPORT)
        .withConfig(c -> c.setHtmlSupport(true)) // allow style/width attrs to survive
        .build();
```

```css
/* shrink embedded media to a fixed/max width in both editor and output */
.ck-content .media,
.ck-content figure.media {
    max-width: 640px;   /* or any width you want */
    margin-inline: auto;
}
.ck-content .media iframe {
    width: 100%;
    aspect-ratio: 16 / 9;  /* keep videos responsive */
}
```

This gives a consistent, smaller video size (just not interactive drag-to-resize handles). I'll wire up real resize handles once the umbrella package exports them. 🤖
